export default {
    images: {
        canvas: {
            backTreesOnly: require('../assets/back-trees-only.png'),
            back: require('../assets/back.png'),
            main: require('../assets/main.png'),
            veil: require('../assets/veil.png'),
            faceMain: require('../assets/face-main.png')
        },
        blink: {
            faceBlinkA: require('../assets/face-blink-A.png'),
            faceBlinkB: require('../assets/face-blink-B.png'),
            faceBlinkC: require('../assets/face-blink-C.png'),
            faceBlinkD: require('../assets/face-blink-D.png'),
            faceBlinkE: require('../assets/face-blink-E.png'),
            faceBlinkF: require('../assets/face-blink-F.png')
        },
        eyePosition: {
            faceEmpty: require('../assets/face-empty.png'),
            faceEyePosition1L1: require('../assets/face-1L1.png'),
            faceEyePosition1L2: require('../assets/face-1L2.png'),
            faceEyePosition1L3: require('../assets/face-1L3.png'),
            faceEyePosition1R1: require('../assets/face-1R1.png'),
            faceEyePosition1R2: require('../assets/face-1R2.png'),
            faceEyePosition1R3: require('../assets/face-1R3.png'),
            faceEyePosition1R4: require('../assets/face-1R4.png'),
            faceEyePosition2L1: require('../assets/face-2L1.png'),
            faceEyePosition2L2: require('../assets/face-2L2.png'),
            faceEyePosition2L3: require('../assets/face-2L3.png'),
            faceEyePosition2L4: require('../assets/face-2L4.png'),
            faceEyePosition2R2: require('../assets/face-2R2.png'),
            faceEyePosition2R3: require('../assets/face-2R3.png'),
            faceEyePosition2R4: require('../assets/face-2R4.png'),
            faceEyePosition3L1: require('../assets/face-3L1.png'),
            faceEyePosition3L2: require('../assets/face-3L2.png'),
            faceEyePosition3L3: require('../assets/face-3L3.png'),
            faceEyePosition3R1: require('../assets/face-3R1.png'),
            faceEyePosition3R2: require('../assets/face-3R2.png'),
            faceEyePosition3R3: require('../assets/face-3R3.png'),
            faceEyePosition4L1: require('../assets/face-4L1.png'),
            faceEyePosition4L2: require('../assets/face-4L2.png'),
            faceEyePosition4L3: require('../assets/face-4L3.png'),
            faceEyePosition4L4: require('../assets/face-4L4.png'),
            faceEyePosition4R1: require('../assets/face-4R1.png'),
            faceEyePosition4R2: require('../assets/face-4R2.png'),
            faceEyePosition4R3: require('../assets/face-4R3.png'),
            faceEyePosition4R4: require('../assets/face-4R4.png'),
            faceEyePosition5L1: require('../assets/face-5L1.png'),
            faceEyePosition5L2: require('../assets/face-5L2.png'),
            faceEyePosition5L3: require('../assets/face-5L3.png'),
            faceEyePosition5L4: require('../assets/face-5L4.png'),
            faceEyePosition5L5: require('../assets/face-5L5.png'),
            faceEyePosition5R1: require('../assets/face-5R1.png'),
            faceEyePosition5R2: require('../assets/face-5R2.png'),
            faceEyePosition5R3: require('../assets/face-5R3.png'),
            faceEyePosition5R4: require('../assets/face-5R4.png'),
            clock800: require('../assets/face-5R4.png'),
            clock900: require('../assets/face-4R4.png'),
            clock915: require('../assets/face-3R3.png'),
            clock930: require('../assets/face-2R4.png'),
            clock945: require('../assets/face-1R4.png'),
            clock1000: require('../assets/face-1R3.png'),
            clock1030: require('../assets/face-1R2.png'),
            clock1100: require('../assets/face-1R1.png'),
            clock1200: require('../assets/face-1L1.png'),
            clock100: require('../assets/face-1L2.png'),
            clock200: require('../assets/face-1L3.png'),
            clock230: require('../assets/face-2L4.png'),
            clock300: require('../assets/face-3L3.png'),
            clock330: require('../assets/face-4L4.png'),
            clock400: require('../assets/face-5L5.png'),
            clock415: require('../assets/face-5L4.png'),
            clock430: require('../assets/face-5L3.png'),
            clock445: require('../assets/face-5L2.png'),
            clock500: require('../assets/face-5L1.png'),
            clock700: require('../assets/face-5R1.png'),
            clock730: require('../assets/face-5R2.png'),
            clock745: require('../assets/face-5R3.png')
        }
    },
    appFont: 'Nothing You Could Do, cursive',
    formFont: 'Cormorant Garamond, serif',
    tracks: {
        "Believe in You": 'https://raw.githubusercontent.com/dvho/dh/master/music/Believe%20in%20You-17.mp3',
        "How Could You Say That": 'https://raw.githubusercontent.com/dvho/dh/master/music/How%20Could%20You%20Say%20That-08.mp3',
        "Fire and Acid Rain": 'https://raw.githubusercontent.com/dvho/dh/master/music/Fire%20and%20Acid%20Rain-12.mp3',
        "I Wish it were Raining": 'https://raw.githubusercontent.com/dvho/dh/master/music/I%20Wish%20It%20Were%20Raining-11.mp3',
        "Forgive": 'https://raw.githubusercontent.com/dvho/dh/master/music/I%20Will%20Not%20Forgive-11.mp3',
        "Bad Place (placeholder)": 'https://freesound.org/data/previews/135/135834_1050391-lq.mp3', //Eventually this will be "Bad Place"
        "Highest Mountain": 'https://raw.githubusercontent.com/dvho/dh/master/music/Highest%20Mountain-11.mp3',
        "Baby Elephant": 'https://raw.githubusercontent.com/dvho/dh/master/music/Baby%20Elephant-06.mp3',
        "Driving and Crying": 'https://raw.githubusercontent.com/dvho/dh/master/music/Driving%20and%20Crying-04.mp3',
        "Here (placeholder)": 'https://freesound.org/data/previews/345/345852_387219-lq.mp3' //Eventually this will be "I'm Just Standing Here"
    }
}
