export default {
    images: {
        backTreesOnly: require('../assets/back-trees-only.png'),
        back: require('../assets/back.png'),
        main: require('../assets/main.png'),
        veil: require('../assets/veil.png'),
        faceMain: require('../assets/face-main.png'),
        faceEmpty: require('../assets/face-empty.png'),
        faceEyePosition3L1: require('../assets/face-3L1.png'),
        faceEyePosition3L2: require('../assets/face-3L2.png'),
        faceEyePosition3L3: require('../assets/face-3L3.png'),
        faceEyePosition3R1: require('../assets/face-3R1.png'),
        faceEyePosition3R2: require('../assets/face-3R2.png'),
        faceEyePosition3R3: require('../assets/face-3R3.png'),
        faceEyePosition2L1: require('../assets/face-2L1.png'),
        faceEyePosition2L2: require('../assets/face-2L2.png'),
        faceEyePosition2L3: require('../assets/face-2L3.png'),
        faceEyePosition2L4: require('../assets/face-2L4.png'),
        faceEyePosition2R2: require('../assets/face-2R2.png'),
        faceEyePosition2R3: require('../assets/face-2R3.png'),
        faceEyePosition1L1: require('../assets/face-1L1.png'),
        faceEyePosition1L2: require('../assets/face-1L2.png'),
        faceEyePosition1L3: require('../assets/face-1L3.png'),
        faceEyePosition1R1: require('../assets/face-1R1.png'),
        faceEyePosition1R2: require('../assets/face-1R2.png'),
        faceEyePosition1R3: require('../assets/face-1R3.png'),
        faceBlinkA: require('../assets/face-blink-A.png'),
        faceBlinkB: require('../assets/face-blink-B.png'),
        faceBlinkC: require('../assets/face-blink-C.png'),
        faceBlinkD: require('../assets/face-blink-D.png'),
        faceBlinkE: require('../assets/face-blink-E.png'),
        faceBlinkF: require('../assets/face-blink-F.png'),
    }
}
